### ISSUE TITLE
Create meaningful README

### ISSUE THREAD

**Issue by augi** [avast/gossip-bot#1]

**Comment by tynovsky** [comment]
Thanks very much for the report, pull requests are warmly appreciated.

**Comment by augi** [comment]
Not my work! :-)

**Comment by tynovsky** [comment]
If it's not your job, please do NOT submit issues!

**Comment by augi** [comment]
My job is to create the issues, not to make the pull requests!

**Comment by tynovsky** [comment]
OK then, sir. We'll work on solving the issue.

**Comment by tynovsky** [comment]
There's one sentence description explaining the purpose of the program. We'll get back to this issue later when we have better implementation.
